name: "Run nox"
description: >
  This composite action runs nox, and includes setting up Python and caching
  the tox environments.
inputs:
  nox-sessions:
    description: "Nox sessions to run (a space-delimited list)"
    required: true
  nox-package:
    description: "Pip requirements for installing nox"
    required: false
    default: "nox"
  nox-posargs:
    description: >
      Additional arguments to the nox command that are available to
      sessions as the "session.posargs" attribute.
    required: false
    default: ""
  python-version:
    description: "Python version"
    required: true
  use-cache:
    description: >
      Whether to cache the nox virtual environments.
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    # For right now, we cannot cache the nox virtual environments because of
    # https://github.com/wntrblm/nox/issues/735. Once that bug is fixed, add a
    # configurable cache prefix and dependency pattern and also cache .nox.
    - name: Cache nox environments
      id: cache-nox
      uses: actions/cache@v3
      if: fromJSON(${{ inputs.use-cache }})
      with:
        path: ~/.cache
        key: nox-pip-${{ inputs.python-version }}

    - name: nox install
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade ${{ inputs.nox-package }}

    - name: Run nox
      shell: bash
      run: nox -s ${{ inputs.nox-sessions }} -- ${{ inputs.nox-posargs }}
