name: "Run nox"
description: >
  This composite action runs nox, and includes setting up Python and caching
  the tox environments.
inputs:
  cache-dependency:
    description: >
      Glob pattern for the additional dependency files to add to the cache
      hash. Normally this should reference either frozen dependencies or
      pyproject.toml files. Due to limitations in the GitHub Actions syntax,
      only one dependency is supported.
    required: false
    default: "pyproject.toml"
  cache-key-prefix:
    description: >
      Prefix for the nox environment cache key. Set to distinguish from
      other caches.
    required: false
    default: "nox"
  nox-sessions:
    description: "Nox sessions to run (a space-delimited list)"
    required: true
  nox-package:
    description: "Pip requirements for installing nox"
    required: false
    default: "nox[uv]"
  nox-posargs:
    description: >
      Additional arguments to the nox command that are available to
      sessions as the "session.posargs" attribute.
    required: false
    default: ""
  python-version:
    description: "Python version"
    required: true
  use-cache:
    description: >
      Whether to cache the nox virtual environments.
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: nox install
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade ${{ inputs.nox-package }}

    - name: Cache nox environments
      id: cache-nox
      uses: actions/cache@v4
      if: inputs.use-cache == 'true'
      with:
        path: .nox
        key: ${{ inputs.cache-key-prefix }}|${{ env.pythonLocation }}|${{ hashFiles('noxfile.py', inputs.cache-dependency) }}

    - name: Run nox
      shell: bash
      run: nox -s ${{ inputs.nox-sessions }} -- ${{ inputs.nox-posargs }}
